[BASIC]
LANGUAGE = ""
COOKIE = ""
SEC_CH_UA = ''
SEC_FETCH_DEST = ""
SEC_FETCH_MODE = ""
USER_AGENT = ""
HOST = "xxx"
MYID = 111
MQTT_USER = ""
MQTT_PASSWORD = ""

[GAME]
bonus = 100
remain_point = 18
sleep = 60
gift_model = false
gift_remain_point = 20
gift_bonus = 100
natural_remain_point = 16
natural_bonus = 100
boom_rate = 0
win_rate = 0.58
natural_mode_time = []
auto_time = []
auto_play = false
play_point = 10000
play_sleep = 60
play_set = [[100, 19], [1000, 18], [10000, 17]]
max_help_bonus = 10000
